package com.example;

import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import io.agroal.api.AgroalDataSource;


@Path("/hello")
public class GreetingResource {

    @Inject
    AgroalDataSource dataSource;


    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() throws Exception{
        //return "Hello from Quarkus REST";

    try (Connection conn = dataSource.getConnection()) {
        System.out.println("Conexão com o banco OK");

         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT 'OK' FROM dual"); {

        rs.next();
        return "Conexão funcionando: " + rs.getString(1);
         }


            //Criar tabela se não existir
            /*try (Statement stmt = conn.createStatement()) {
                stmt.execute("""
                    CREATE TABLE mensagens (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        texto VARCHAR2(100)
                    )
                """);
            } catch (SQLException e) {
                // Ignora erro se a tabela já existir
                
                if (!e.getMessage().contains("ORA-00955")) { // nome já utilizado
                    throw e;
                }
            }*/

            // Inserir um registro
            /*try (PreparedStatement ps =
                     conn.prepareStatement("INSERT INTO mensagens (texto) VALUES (?)")) {
                ps.setString(1, "Teste");
                ps.executeUpdate();
            }

            // Consultar o registro
            try (PreparedStatement ps =
                     conn.prepareStatement("SELECT texto FROM mensagens");
                 ResultSet rs = ps.executeQuery()) {

                if (rs.next()) {
                    return "Banco respondeu: " + rs.getString(1);
                }
            }*/
    }

    //return "Nenhum dado encontrado";
}

}


